### ISSUE TITLE
docker compos exec not working

### ISSUE THREAD

**Issue by Mase3206** [Mase3206/django-multihost#4]
Using /django/fall24/awesome-test/docker-compose.site.yml
Traceback (most recent call last):
  File "/usr/local/bin/deploy", line 135, in <module>
    main(args)
  File "/usr/local/bin/deploy", line 110, in main
    args.func(args)
  File "/django/source/actions.py", line 172, in execute
    runCommand(args, command)
  File "/django/source/actions.py", line 84, in runCommand
    subprocess.run(command)
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the runCommand function to join the command list into a string before passing it to subprocess.run()

You can review changes in this commit: https://github.com/lattaai13/Mase3206-django-multihost-4/commit/7f8109cbe09f5d2766c494e1d2b72016e2794f4d.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Mase3206** [comment]
Resolved.
